"""IceCat item info caching model

Revision ID: bbb48220c3fa
Revises: 4db216b164e0
Create Date: 2022-02-15 17:58:07.954324

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = 'bbb48220c3fa'
down_revision = '4db216b164e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icecat_info',
    sa.Column('ean', sa.String(length=13), nullable=False),
    sa.Column('info', sa.JSON(), nullable=False),
    sa.Column('requested_by', ormar.fields.sqlalchemy_uuid.CHAR(36), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name='fk_icecat_info_users_id_requested_by'),
    sa.PrimaryKeyConstraint('ean')
    )
    op.create_index(op.f('ix_icecat_info_ean'), 'icecat_info', ['ean'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_icecat_info_ean'), table_name='icecat_info')
    op.drop_table('icecat_info')
    # ### end Alembic commands ###
